### ISSUE TITLE
Runtime error with costools.splittag

### ISSUE THREAD

**Issue by afeinstein20** [spacetelescope/costools#25]
Hi! I've used the `costools.splittag.splittag` routine to extract the time-tag observations in the past. For a recent HST visit, it seems to fail for 1 out of the 5 orbits we got. I'm getting the following error:

```
~/Documents/GitHub/cos_flares/src/cos_reduction.py in split_corrtag(self, output_path, increment, starttime, endtime, time_list)
    103                               endtime=endtime, time_list=time_list)
    104 
--> 105             splittag.splittag(corrtag_b, os.path.join(output_path,
    106                                                       'split_{}'.format(self.rootname[i])),
    107                               increment=increment, starttime=starttime,

~/opt/anaconda3/lib/python3.9/site-packages/costools/splittag.py in splittag(infiles, outroot, starttime, increment, endtime, time_list, verbosity)
    152         time_list = None
    153 
--> 154     SPLT.splittag(infiles=infiles, outroot=outroot,
    155                   starttime=starttime, increment=increment, endtime=endtime,
    156                   time_list=time_list, verbosity=verbosity)

~/opt/anaconda3/lib/python3.9/site-packages/calcos/splittag.py in splittag(infiles, outroot, starttime, increment, endtime, time_list, verbosity)
     50     inlist = glob.glob(infiles)
     51     for input in inlist:
---> 52         splitOneTag(input, outroot, starttime, increment, endtime,
     53                     time_list, verbosity)
     54 

~/opt/anaconda3/lib/python3.9/site-packages/calcos/splittag.py in splitOneTag(input, outroot, starttime, increment, endtime, time_list, verbosity)
    133             ofd.append(out_gti_hdu)
    134 
--> 135         out_timeline_hdu = createNewTimeline(timeline_hdu, t0, t1)
    136         if out_timeline_hdu is not None:
    137             ofd.append(out_timeline_hdu)

~/opt/anaconda3/lib/python3.9/site-packages/calcos/splittag.py in createNewTimeline(timeline_hdu, t0, t1)
    673         # of the input TIMELINE table.
    674         # This implicitly assumes that the time increment is one second.
--> 675         (i_start, i_end)= ccos.range(time_col, t0, math.ceil(t1) + 0.1)
    676         out_nrows = i_end - i_start
    677     else:

RuntimeError: (30, 60.1) does not overlap the time array
```

Any insight into what's causing this bug would be greatly appreciated -- thanks!!

**Comment by afeinstein20** [comment]
Yes! It's from Program 16164 > data set `LEBB02010` > file prefix `lebb02nzq`

**Comment by afeinstein20** [comment]
Huh, interesting. Thanks for getting back to me @stscirij ! Do you think this would this be worth raising on the CALCOS issues? or something I would need to hack on my own?

**Comment by stscirij** [comment]
I'm looking into it right now, it's not obvious why the spectrum wasn't found.  You could try a workaround of using the timeline from the _a spectrum, although you may need to see how the _b timeline compares to the _a timeline for the other members of the association to see if there are additional offsets to apply to the _a timeline to make it work with the _b timeline.

**Comment by afeinstein20** [comment]
hi! I just wanted to quickly follow up on this issue in case there has been some resolution (I'm about to jump back into this analysis... can't believe a month has passed since opening the issue...)

**Comment by stenhasselquist** [comment]
Hi Adina,

We've determined that the wavecal region of this exposure was affected by a hot spot, which resulted in no wavelength calibration. So this is unlucky for you, but fortunate for us in that you helped us identify a new hot spot!

Eventually we will create a new SPOTTAB that will take automatically mask out these events, but in the meantime, there are a few options to fix your data so that this exposure is successfully calibrated. I will briefly describe one option below, but I think the best way forward is probably for you to submit an HST Help Desk ticket, and I'll pick it up and help you there. 

The hot spot roughly occupies a region of the detector with 6850 < RAWX < 6950 and 570 < RAWY < 610. For the failed exposure, you could identify these events and remove them from the rawtag file. Then, recalibrate the entire dataset with CalCOS, and then run splittag in the way you wanted to originally. I haven't tested this myself yet, but I think it should work.
